import CoreModel

// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Source of truth: Tooling/Data/beverages.json
// Regenerate: bash Tooling/generate_brand_table.sh
// 161 brands, sorted by descending match-key length (most specific wins).

struct BrandEntry: Sendable {
    let key: String        // lowercased substring matched against the drink name
    let label: String      // display name shown in the estimate note
    let category: BeverageCategory
    let abv: Double        // percent
}

let generatedBrandTable: [BrandEntry] = [
    BrandEntry(key: "ballast point grapefruit sculpin", label: "Ballast Point Grapefruit Sculpin", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "sierra nevada hazy little thing", label: "Sierra Nevada Hazy Little Thing", category: .draftBeer, abv: 6.7),
    BrandEntry(key: "weihenstephaner hefeweizen", label: "Weihenstephaner Hefeweizen", category: .draftBeer, abv: 5.4),
    BrandEntry(key: "angry orchard crisp apple", label: "Angry Orchard Crisp Apple", category: .cider, abv: 5.0),
    BrandEntry(key: "michelob ultra pure gold", label: "Michelob Ultra Pure Gold", category: .bottledBeer, abv: 4.3),
    BrandEntry(key: "deschutes fresh squeezed", label: "Deschutes Fresh Squeezed", category: .draftBeer, abv: 6.4),
    BrandEntry(key: "lagunitas little sumpin", label: "Lagunitas Little Sumpin", category: .draftBeer, abv: 7.5),
    BrandEntry(key: "topo chico hard seltzer", label: "Topo Chico Hard Seltzer", category: .seltzer, abv: 4.7),
    BrandEntry(key: "michelob ultra seltzer", label: "Michelob Ultra Seltzer", category: .seltzer, abv: 4.0),
    BrandEntry(key: "sierra nevada pale ale", label: "Sierra Nevada Pale Ale", category: .draftBeer, abv: 5.6),
    BrandEntry(key: "dogfish head 90 minute", label: "Dogfish Head 90 Minute", category: .draftBeer, abv: 9.0),
    BrandEntry(key: "dogfish head 60 minute", label: "Dogfish Head 60 Minute", category: .draftBeer, abv: 6.0),
    BrandEntry(key: "golden road mango cart", label: "Golden Road Mango Cart", category: .draftBeer, abv: 4.0),
    BrandEntry(key: "great lakes dortmunder", label: "Great Lakes Dortmunder", category: .draftBeer, abv: 5.1),
    BrandEntry(key: "sierra nevada torpedo", label: "Sierra Nevada Torpedo", category: .draftBeer, abv: 7.2),
    BrandEntry(key: "ballast point sculpin", label: "Ballast Point Sculpin", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "miller genuine draft", label: "Miller Genuine Draft", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "corona non-alcoholic", label: "Corona Non-Alcoholic", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "founders all day ipa", label: "Founders All Day IPA", category: .draftBeer, abv: 4.7),
    BrandEntry(key: "new belgium fat tire", label: "New Belgium Fat Tire", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "left hand milk stout", label: "Left Hand Milk Stout", category: .draftBeer, abv: 6.0),
    BrandEntry(key: "mike's hard lemonade", label: "Mike's Hard Lemonade", category: .seltzer, abv: 5.0),
    BrandEntry(key: "athletic upside dawn", label: "Athletic Upside Dawn", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "budweiser select 55", label: "Budweiser Select 55", category: .bottledBeer, abv: 2.4),
    BrandEntry(key: "michelob ultra zero", label: "Michelob Ultra Zero", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "michelob amber bock", label: "Michelob Amber Bock", category: .bottledBeer, abv: 5.2),
    BrandEntry(key: "corona hard seltzer", label: "Corona Hard Seltzer", category: .seltzer, abv: 4.5),
    BrandEntry(key: "founders solid gold", label: "Founders Solid Gold", category: .draftBeer, abv: 4.5),
    BrandEntry(key: "bud light platinum", label: "Bud Light Platinum", category: .bottledBeer, abv: 6.0),
    BrandEntry(key: "bell's two hearted", label: "Bell's Two Hearted", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "elysian space dust", label: "Elysian Space Dust", category: .draftBeer, abv: 8.2),
    BrandEntry(key: "athletic free wave", label: "Athletic Free Wave", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "bud light seltzer", label: "Bud Light Seltzer", category: .seltzer, abv: 5.0),
    BrandEntry(key: "michelob ultra na", label: "Michelob Ultra NA", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "pabst blue ribbon", label: "Pabst Blue Ribbon", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "genesee cream ale", label: "Genesee Cream Ale", category: .bottledBeer, abv: 5.1),
    BrandEntry(key: "stella artois 0.0", label: "Stella Artois 0.0", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "high noon tequila", label: "High Noon Tequila", category: .seltzer, abv: 4.5),
    BrandEntry(key: "twisted tea light", label: "Twisted Tea Light", category: .seltzer, abv: 4.0),
    BrandEntry(key: "athletic run wild", label: "Athletic Run Wild", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "la marca prosecco", label: "La Marca Prosecco", category: .wineGlass, abv: 11.0),
    BrandEntry(key: "budweiser select", label: "Budweiser Select", category: .bottledBeer, abv: 4.3),
    BrandEntry(key: "miller high life", label: "Miller High Life", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "guinness draught", label: "Guinness Draught", category: .draftBeer, abv: 4.2),
    BrandEntry(key: "white claw surge", label: "White Claw Surge", category: .seltzer, abv: 8.0),
    BrandEntry(key: "yuengling light", label: "Yuengling Light", category: .bottledBeer, abv: 3.8),
    BrandEntry(key: "modelo especial", label: "Modelo Especial", category: .bottledBeer, abv: 4.4),
    BrandEntry(key: "dos equis amber", label: "Dos Equis Amber", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "dos equis lager", label: "Dos Equis Lager", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "pilsner urquell", label: "Pilsner Urquell", category: .bottledBeer, abv: 4.4),
    BrandEntry(key: "bud light lime", label: "Bud Light Lime", category: .bottledBeer, abv: 4.2),
    BrandEntry(key: "budweiser zero", label: "Budweiser Zero", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "michelob ultra", label: "Michelob Ultra", category: .bottledBeer, abv: 4.2),
    BrandEntry(key: "keystone light", label: "Keystone Light", category: .bottledBeer, abv: 4.1),
    BrandEntry(key: "corona premier", label: "Corona Premier", category: .bottledBeer, abv: 4.0),
    BrandEntry(key: "heineken light", label: "Heineken Light", category: .bottledBeer, abv: 3.3),
    BrandEntry(key: "kona longboard", label: "Kona Longboard", category: .draftBeer, abv: 4.6),
    BrandEntry(key: "allagash white", label: "Allagash White", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "downeast cider", label: "Downeast Cider", category: .cider, abv: 5.1),
    BrandEntry(key: "zonin prosecco", label: "Zonin Prosecco", category: .wineGlass, abv: 11.0),
    BrandEntry(key: "coors banquet", label: "Coors Banquet", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "natural light", label: "Natural Light", category: .bottledBeer, abv: 4.2),
    BrandEntry(key: "old milwaukee", label: "Old Milwaukee", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "stella artois", label: "Stella Artois", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "guinness zero", label: "Guinness Zero", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "sierra nevada", label: "Sierra Nevada", category: .draftBeer, abv: 5.6),
    BrandEntry(key: "lagunitas ipa", label: "Lagunitas IPA", category: .draftBeer, abv: 6.2),
    BrandEntry(key: "bell's oberon", label: "Bell's Oberon", category: .draftBeer, abv: 5.8),
    BrandEntry(key: "voodoo ranger", label: "Voodoo Ranger", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "kona big wave", label: "Kona Big Wave", category: .draftBeer, abv: 4.4),
    BrandEntry(key: "weihenstephan", label: "Weihenstephan", category: .draftBeer, abv: 5.4),
    BrandEntry(key: "alaskan amber", label: "Alaskan Amber", category: .draftBeer, abv: 5.3),
    BrandEntry(key: "surly axe man", label: "Surly Axe Man", category: .draftBeer, abv: 7.2),
    BrandEntry(key: "angry orchard", label: "Angry Orchard", category: .cider, abv: 5.0),
    BrandEntry(key: "white claw na", label: "White Claw NA", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "simply spiked", label: "Simply Spiked", category: .seltzer, abv: 5.0),
    BrandEntry(key: "keystone ice", label: "Keystone Ice", category: .bottledBeer, abv: 5.9),
    BrandEntry(key: "rolling rock", label: "Rolling Rock", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "corona light", label: "Corona Light", category: .bottledBeer, abv: 4.0),
    BrandEntry(key: "corona extra", label: "Corona Extra", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "modelo negra", label: "Modelo Negra", category: .bottledBeer, abv: 5.4),
    BrandEntry(key: "heineken 0.0", label: "Heineken 0.0", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "amstel light", label: "Amstel Light", category: .bottledBeer, abv: 3.5),
    BrandEntry(key: "guinness 0.0", label: "Guinness 0.0", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "founders kbs", label: "Founders KBS", category: .draftBeer, abv: 12.0),
    BrandEntry(key: "franziskaner", label: "Franziskaner", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "mighty swell", label: "Mighty Swell", category: .seltzer, abv: 5.0),
    BrandEntry(key: "smirnoff ice", label: "Smirnoff Ice", category: .seltzer, abv: 4.5),
    BrandEntry(key: "coors light", label: "Coors Light", category: .bottledBeer, abv: 4.2),
    BrandEntry(key: "miller lite", label: "Miller Lite", category: .bottledBeer, abv: 4.2),
    BrandEntry(key: "busch light", label: "Busch Light", category: .bottledBeer, abv: 4.1),
    BrandEntry(key: "natural ice", label: "Natural Ice", category: .bottledBeer, abv: 5.9),
    BrandEntry(key: "labatt blue", label: "Labatt Blue", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "corona cero", label: "Corona Cero", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "heineken na", label: "Heineken NA", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "beck's blue", label: "Beck's Blue", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "smithwick's", label: "Smithwick's", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "shiner bock", label: "Shiner Bock", category: .bottledBeer, abv: 4.4),
    BrandEntry(key: "spotted cow", label: "Spotted Cow", category: .draftBeer, abv: 4.8),
    BrandEntry(key: "twisted tea", label: "Twisted Tea", category: .seltzer, abv: 5.0),
    BrandEntry(key: "mike's hard", label: "Mike's Hard", category: .seltzer, abv: 5.0),
    BrandEntry(key: "cayman jack", label: "Cayman Jack", category: .seltzer, abv: 5.8),
    BrandEntry(key: "run wild na", label: "Run Wild NA", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "red stripe", label: "Red Stripe", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "presidente", label: "Presidente", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "mango cart", label: "Mango Cart", category: .draftBeer, abv: 4.0),
    BrandEntry(key: "warsteiner", label: "Warsteiner", category: .draftBeer, abv: 4.8),
    BrandEntry(key: "white claw", label: "White Claw", category: .seltzer, abv: 5.0),
    BrandEntry(key: "long drink", label: "Long Drink", category: .seltzer, abv: 5.5),
    BrandEntry(key: "bud light", label: "Bud Light", category: .bottledBeer, abv: 4.2),
    BrandEntry(key: "budweiser", label: "Budweiser", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "miller 64", label: "Miller 64", category: .bottledBeer, abv: 2.8),
    BrandEntry(key: "busch ice", label: "Busch Ice", category: .bottledBeer, abv: 5.9),
    BrandEntry(key: "yuengling", label: "Yuengling", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "dos equis", label: "Dos Equis", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "newcastle", label: "Newcastle", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "lagunitas", label: "Lagunitas", category: .draftBeer, abv: 6.2),
    BrandEntry(key: "stone ipa", label: "Stone IPA", category: .draftBeer, abv: 6.9),
    BrandEntry(key: "blue moon", label: "Blue Moon", category: .draftBeer, abv: 5.4),
    BrandEntry(key: "strongbow", label: "Strongbow", category: .cider, abv: 5.0),
    BrandEntry(key: "woodchuck", label: "Woodchuck", category: .cider, abv: 5.0),
    BrandEntry(key: "bold rock", label: "Bold Rock", category: .cider, abv: 4.7),
    BrandEntry(key: "high noon", label: "High Noon", category: .seltzer, abv: 4.5),
    BrandEntry(key: "bon & viv", label: "Bon & Viv", category: .seltzer, abv: 4.5),
    BrandEntry(key: "freixenet", label: "Freixenet", category: .wineGlass, abv: 11.5),
    BrandEntry(key: "bud zero", label: "Bud Zero", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "pacifico", label: "Pacifico", category: .bottledBeer, abv: 4.4),
    BrandEntry(key: "victoria", label: "Victoria", category: .bottledBeer, abv: 4.0),
    BrandEntry(key: "heineken", label: "Heineken", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "foster's", label: "Foster's", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "tsingtao", label: "Tsingtao", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "guinness", label: "Guinness", category: .draftBeer, abv: 4.2),
    BrandEntry(key: "founders", label: "Founders", category: .draftBeer, abv: 5.5),
    BrandEntry(key: "fat tire", label: "Fat Tire", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "paulaner", label: "Paulaner", category: .draftBeer, abv: 5.5),
    BrandEntry(key: "downeast", label: "Downeast", category: .cider, abv: 5.1),
    BrandEntry(key: "surfside", label: "Surfside", category: .seltzer, abv: 4.5),
    BrandEntry(key: "carbliss", label: "Carbliss", category: .seltzer, abv: 5.0),
    BrandEntry(key: "cutwater", label: "Cutwater", category: .seltzer, abv: 7.0),
    BrandEntry(key: "athletic", label: "Athletic", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "o'doul's", label: "O'Doul's", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "schlitz", label: "Schlitz", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "sapporo", label: "Sapporo", category: .bottledBeer, abv: 4.9),
    BrandEntry(key: "hamm's", label: "Hamm's", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "corona", label: "Corona", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "modelo", label: "Modelo", category: .bottledBeer, abv: 4.4),
    BrandEntry(key: "tecate", label: "Tecate", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "dos xx", label: "Dos XX", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "peroni", label: "Peroni", category: .bottledBeer, abv: 5.1),
    BrandEntry(key: "beck's", label: "Beck's", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "spaten", label: "Spaten", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "korbel", label: "Korbel", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "busch", label: "Busch", category: .bottledBeer, abv: 4.3),
    BrandEntry(key: "asahi", label: "Asahi", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "kirin", label: "Kirin", category: .bottledBeer, abv: 4.9),
    BrandEntry(key: "truly", label: "Truly", category: .seltzer, abv: 5.0),
    BrandEntry(key: "nutrl", label: "Nutrl", category: .seltzer, abv: 4.5),
    BrandEntry(key: "vizzy", label: "Vizzy", category: .seltzer, abv: 5.0),
    BrandEntry(key: "press", label: "Press", category: .seltzer, abv: 4.0),
    BrandEntry(key: "bass", label: "Bass", category: .bottledBeer, abv: 5.1),
    BrandEntry(key: "pbr", label: "PBR", category: .bottledBeer, abv: 4.7),
]
