import CoreModel

// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Source of truth: Tooling/Data/beverages.json
// Regenerate: bash Tooling/generate_brand_table.sh
// 655 brands, sorted by descending match-key length (most specific wins).

struct BrandEntry: Sendable {
    let key: String        // lowercased substring matched against the drink name
    let label: String      // display name shown in the estimate note
    let category: BeverageCategory
    let abv: Double        // percent
}

let generatedBrandTable: [BrandEntry] = [
    BrandEntry(key: "belching beaver peanut butter milk stout", label: "Belching Beaver Peanut Butter Milk Stout", category: .draftBeer, abv: 5.3),
    BrandEntry(key: "ballast point grapefruit sculpin", label: "Ballast Point Grapefruit Sculpin", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "sierra nevada hazy little thing", label: "Sierra Nevada Hazy Little Thing", category: .draftBeer, abv: 6.7),
    BrandEntry(key: "sierra nevada big little thing", label: "Sierra Nevada Big Little Thing", category: .draftBeer, abv: 9.0),
    BrandEntry(key: "great lakes edmund fitzgerald", label: "Great Lakes Edmund Fitzgerald", category: .draftBeer, abv: 6.0),
    BrandEntry(key: "russian river pliny the elder", label: "Russian River Pliny the Elder", category: .draftBeer, abv: 8.0),
    BrandEntry(key: "captain lawrence freshchester", label: "Captain Lawrence Freshchester", category: .draftBeer, abv: 6.0),
    BrandEntry(key: "deschutes black butte porter", label: "Deschutes Black Butte Porter", category: .draftBeer, abv: 5.5),
    BrandEntry(key: "creature comforts tropicalia", label: "Creature Comforts Tropicalia", category: .draftBeer, abv: 6.6),
    BrandEntry(key: "coney island mermaid pilsner", label: "Coney Island Mermaid Pilsner", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "figueroa mountain danish red", label: "Figueroa Mountain Danish Red", category: .draftBeer, abv: 5.1),
    BrandEntry(key: "samuel smith's oatmeal stout", label: "Samuel Smith's Oatmeal Stout", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "goose island bourbon county", label: "Goose Island Bourbon County", category: .bottledBeer, abv: 14.0),
    BrandEntry(key: "firestone walker union jack", label: "Firestone Walker Union Jack", category: .draftBeer, abv: 7.5),
    BrandEntry(key: "breckenridge vanilla porter", label: "Breckenridge Vanilla Porter", category: .draftBeer, abv: 5.4),
    BrandEntry(key: "weihenstephaner alkoholfrei", label: "Weihenstephaner Alkoholfrei", category: .nonAlcoholic, abv: 0.5),
    BrandEntry(key: "austin eastciders pineapple", label: "Austin Eastciders Pineapple", category: .cider, abv: 5.0),
    BrandEntry(key: "weihenstephaner hefeweizen", label: "Weihenstephaner Hefeweizen", category: .draftBeer, abv: 5.4),
    BrandEntry(key: "voodoo ranger imperial ipa", label: "Voodoo Ranger Imperial IPA", category: .draftBeer, abv: 9.0),
    BrandEntry(key: "firestone walker mind haze", label: "Firestone Walker Mind Haze", category: .draftBeer, abv: 6.2),
    BrandEntry(key: "green flash west coast ipa", label: "Green Flash West Coast IPA", category: .draftBeer, abv: 8.1),
    BrandEntry(key: "lost coast tangerine wheat", label: "Lost Coast Tangerine Wheat", category: .draftBeer, abv: 5.5),
    BrandEntry(key: "boulevard unfiltered wheat", label: "Boulevard Unfiltered Wheat", category: .draftBeer, abv: 4.4),
    BrandEntry(key: "toppling goliath pseudosue", label: "Toppling Goliath PseudoSue", category: .draftBeer, abv: 5.8),
    BrandEntry(key: "founders backwoods bastard", label: "Founders Backwoods Bastard", category: .draftBeer, abv: 11.6),
    BrandEntry(key: "untitled art non-alcoholic", label: "Untitled Art Non-Alcoholic", category: .nonAlcoholic, abv: 0.5),
    BrandEntry(key: "angry orchard crisp apple", label: "Angry Orchard Crisp Apple", category: .cider, abv: 5.0),
    BrandEntry(key: "sierra nevada celebration", label: "Sierra Nevada Celebration", category: .draftBeer, abv: 6.8),
    BrandEntry(key: "lagunitas hoppy refresher", label: "Lagunitas Hoppy Refresher", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "great lakes christmas ale", label: "Great Lakes Christmas Ale", category: .draftBeer, abv: 7.5),
    BrandEntry(key: "angry orchard green apple", label: "Angry Orchard Green Apple", category: .cider, abv: 5.0),
    BrandEntry(key: "bell's lager of the lakes", label: "Bell's Lager of the Lakes", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "voodoo ranger fruit force", label: "Voodoo Ranger Fruit Force", category: .draftBeer, abv: 8.0),
    BrandEntry(key: "mother earth cali creamin", label: "Mother Earth Cali Creamin", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "little creatures pale ale", label: "Little Creatures Pale Ale", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "michelob ultra pure gold", label: "Michelob Ultra Pure Gold", category: .bottledBeer, abv: 4.3),
    BrandEntry(key: "deschutes fresh squeezed", label: "Deschutes Fresh Squeezed", category: .draftBeer, abv: 6.4),
    BrandEntry(key: "founders breakfast stout", label: "Founders Breakfast Stout", category: .draftBeer, abv: 8.3),
    BrandEntry(key: "voodoo ranger juicy haze", label: "Voodoo Ranger Juicy Haze", category: .draftBeer, abv: 7.5),
    BrandEntry(key: "north coast old rasputin", label: "North Coast Old Rasputin", category: .draftBeer, abv: 9.0),
    BrandEntry(key: "ninkasi total domination", label: "Ninkasi Total Domination", category: .draftBeer, abv: 6.7),
    BrandEntry(key: "21st amendment brew free", label: "21st Amendment Brew Free", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "angry orchard unfiltered", label: "Angry Orchard Unfiltered", category: .cider, abv: 5.5),
    BrandEntry(key: "brooklyn special effects", label: "Brooklyn Special Effects", category: .nonAlcoholic, abv: 0.4),
    BrandEntry(key: "blue point toasted lager", label: "Blue Point Toasted Lager", category: .draftBeer, abv: 5.5),
    BrandEntry(key: "sierra nevada summerfest", label: "Sierra Nevada Summerfest", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "modern times black house", label: "Modern Times Black House", category: .draftBeer, abv: 5.8),
    BrandEntry(key: "creature comforts athena", label: "Creature Comforts Athena", category: .draftBeer, abv: 4.5),
    BrandEntry(key: "weihenstephaner original", label: "Weihenstephaner Original", category: .draftBeer, abv: 5.1),
    BrandEntry(key: "samuel smith's nut brown", label: "Samuel Smith's Nut Brown", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "hitachino nest white ale", label: "Hitachino Nest White Ale", category: .bottledBeer, abv: 5.5),
    BrandEntry(key: "lagunitas little sumpin", label: "Lagunitas Little Sumpin", category: .draftBeer, abv: 7.5),
    BrandEntry(key: "topo chico hard seltzer", label: "Topo Chico Hard Seltzer", category: .seltzer, abv: 4.7),
    BrandEntry(key: "sam adams just the haze", label: "Sam Adams Just the Haze", category: .nonAlcoholic, abv: 0.5),
    BrandEntry(key: "founders centennial ipa", label: "Founders Centennial IPA", category: .draftBeer, abv: 7.2),
    BrandEntry(key: "dogfish head 120 minute", label: "Dogfish Head 120 Minute", category: .bottledBeer, abv: 18.0),
    BrandEntry(key: "alesmith speedway stout", label: "AleSmith Speedway Stout", category: .bottledBeer, abv: 12.0),
    BrandEntry(key: "twisted tea half & half", label: "Twisted Tea Half & Half", category: .seltzer, abv: 5.0),
    BrandEntry(key: "castle danger cream ale", label: "Castle Danger Cream Ale", category: .draftBeer, abv: 5.5),
    BrandEntry(key: "russian river blind pig", label: "Russian River Blind Pig", category: .draftBeer, abv: 6.1),
    BrandEntry(key: "wasatch polygamy porter", label: "Wasatch Polygamy Porter", category: .draftBeer, abv: 4.0),
    BrandEntry(key: "michelob ultra seltzer", label: "Michelob Ultra Seltzer", category: .seltzer, abv: 4.0),
    BrandEntry(key: "sierra nevada pale ale", label: "Sierra Nevada Pale Ale", category: .draftBeer, abv: 5.6),
    BrandEntry(key: "dogfish head 90 minute", label: "Dogfish Head 90 Minute", category: .draftBeer, abv: 9.0),
    BrandEntry(key: "dogfish head 60 minute", label: "Dogfish Head 60 Minute", category: .draftBeer, abv: 6.0),
    BrandEntry(key: "golden road mango cart", label: "Golden Road Mango Cart", category: .draftBeer, abv: 4.0),
    BrandEntry(key: "great lakes dortmunder", label: "Great Lakes Dortmunder", category: .draftBeer, abv: 5.1),
    BrandEntry(key: "guinness foreign extra", label: "Guinness Foreign Extra", category: .bottledBeer, abv: 7.5),
    BrandEntry(key: "half acre daisy cutter", label: "Half Acre Daisy Cutter", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "founders dirty bastard", label: "Founders Dirty Bastard", category: .draftBeer, abv: 8.5),
    BrandEntry(key: "cigar city florida man", label: "Cigar City Florida Man", category: .draftBeer, abv: 7.5),
    BrandEntry(key: "lost coast great white", label: "Lost Coast Great White", category: .draftBeer, abv: 4.8),
    BrandEntry(key: "terrapin hopsecutioner", label: "Terrapin Hopsecutioner", category: .draftBeer, abv: 7.3),
    BrandEntry(key: "great divide titan ipa", label: "Great Divide Titan IPA", category: .draftBeer, abv: 7.1),
    BrandEntry(key: "saint arnold lawnmower", label: "Saint Arnold Lawnmower", category: .draftBeer, abv: 4.9),
    BrandEntry(key: "topo chico ranch water", label: "Topo Chico Ranch Water", category: .seltzer, abv: 4.7),
    BrandEntry(key: "simply spiked lemonade", label: "Simply Spiked Lemonade", category: .seltzer, abv: 5.0),
    BrandEntry(key: "lone river ranch water", label: "Lone River Ranch Water", category: .seltzer, abv: 4.0),
    BrandEntry(key: "jack's abby post shift", label: "Jack's Abby Post Shift", category: .draftBeer, abv: 4.7),
    BrandEntry(key: "dogfish head seaquench", label: "Dogfish Head SeaQuench", category: .draftBeer, abv: 4.9),
    BrandEntry(key: "boulevard space camper", label: "Boulevard Space Camper", category: .draftBeer, abv: 6.0),
    BrandEntry(key: "pizza port swami's ipa", label: "Pizza Port Swami's IPA", category: .draftBeer, abv: 6.8),
    BrandEntry(key: "coronado weekend vibes", label: "Coronado Weekend Vibes", category: .draftBeer, abv: 6.7),
    BrandEntry(key: "terrapin luau krunkles", label: "Terrapin Luau Krunkles", category: .draftBeer, abv: 6.1),
    BrandEntry(key: "wicked weed pernicious", label: "Wicked Weed Pernicious", category: .draftBeer, abv: 7.3),
    BrandEntry(key: "funky buddha floridian", label: "Funky Buddha Floridian", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "revolver blood & honey", label: "Revolver Blood & Honey", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "russian river sts pils", label: "Russian River STS Pils", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "theakston old peculier", label: "Theakston Old Peculier", category: .draftBeer, abv: 5.6),
    BrandEntry(key: "angry orchard hardcore", label: "Angry Orchard Hardcore", category: .cider, abv: 8.0),
    BrandEntry(key: "woodchuck granny smith", label: "Woodchuck Granny Smith", category: .cider, abv: 5.0),
    BrandEntry(key: "jaume serra cristalino", label: "Jaume Serra Cristalino", category: .wineGlass, abv: 11.5),
    BrandEntry(key: "sierra nevada torpedo", label: "Sierra Nevada Torpedo", category: .draftBeer, abv: 7.2),
    BrandEntry(key: "ballast point sculpin", label: "Ballast Point Sculpin", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "michelob golden light", label: "Michelob Golden Light", category: .bottledBeer, abv: 4.1),
    BrandEntry(key: "yuengling black & tan", label: "Yuengling Black & Tan", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "peroni nastro azzurro", label: "Peroni Nastro Azzurro", category: .bottledBeer, abv: 5.1),
    BrandEntry(key: "sam adams octoberfest", label: "Sam Adams Octoberfest", category: .bottledBeer, abv: 5.3),
    BrandEntry(key: "sixpoint sweet action", label: "Sixpoint Sweet Action", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "southern tier pumking", label: "Southern Tier Pumking", category: .draftBeer, abv: 8.6),
    BrandEntry(key: "victory golden monkey", label: "Victory Golden Monkey", category: .bottledBeer, abv: 9.5),
    BrandEntry(key: "deschutes mirror pond", label: "Deschutes Mirror Pond", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "bear republic racer 5", label: "Bear Republic Racer 5", category: .draftBeer, abv: 7.5),
    BrandEntry(key: "natural light seltzer", label: "Natural Light Seltzer", category: .seltzer, abv: 6.0),
    BrandEntry(key: "cayman jack margarita", label: "Cayman Jack Margarita", category: .seltzer, abv: 5.8),
    BrandEntry(key: "night shift whirlpool", label: "Night Shift Whirlpool", category: .draftBeer, abv: 4.5),
    BrandEntry(key: "two roads road 2 ruin", label: "Two Roads Road 2 Ruin", category: .draftBeer, abv: 8.0),
    BrandEntry(key: "off color troublesome", label: "Off Color Troublesome", category: .draftBeer, abv: 4.3),
    BrandEntry(key: "scofflaw basement ipa", label: "Scofflaw Basement IPA", category: .draftBeer, abv: 6.5),
    BrandEntry(key: "great notion juice jr", label: "Great Notion Juice Jr", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "bale breaker field 41", label: "Bale Breaker Field 41", category: .draftBeer, abv: 4.5),
    BrandEntry(key: "weihenstephaner vitus", label: "Weihenstephaner Vitus", category: .draftBeer, abv: 7.7),
    BrandEntry(key: "duchesse de bourgogne", label: "Duchesse de Bourgogne", category: .bottledBeer, abv: 6.2),
    BrandEntry(key: "fuller's london pride", label: "Fuller's London Pride", category: .draftBeer, abv: 4.7),
    BrandEntry(key: "belhaven scottish ale", label: "Belhaven Scottish Ale", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "coopers sparkling ale", label: "Coopers Sparkling Ale", category: .bottledBeer, abv: 5.8),
    BrandEntry(key: "bold rock vintage dry", label: "Bold Rock Vintage Dry", category: .cider, abv: 6.0),
    BrandEntry(key: "budweiser prohibition", label: "Budweiser Prohibition", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "miller genuine draft", label: "Miller Genuine Draft", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "corona non-alcoholic", label: "Corona Non-Alcoholic", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "founders all day ipa", label: "Founders All Day IPA", category: .draftBeer, abv: 4.7),
    BrandEntry(key: "new belgium fat tire", label: "New Belgium Fat Tire", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "left hand milk stout", label: "Left Hand Milk Stout", category: .draftBeer, abv: 6.0),
    BrandEntry(key: "mike's hard lemonade", label: "Mike's Hard Lemonade", category: .seltzer, abv: 5.0),
    BrandEntry(key: "athletic upside dawn", label: "Athletic Upside Dawn", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "erdinger alkoholfrei", label: "Erdinger Alkoholfrei", category: .nonAlcoholic, abv: 0.5),
    BrandEntry(key: "guinness extra stout", label: "Guinness Extra Stout", category: .bottledBeer, abv: 5.6),
    BrandEntry(key: "sam adams summer ale", label: "Sam Adams Summer Ale", category: .bottledBeer, abv: 5.3),
    BrandEntry(key: "troegs perpetual ipa", label: "Troegs Perpetual IPA", category: .draftBeer, abv: 7.5),
    BrandEntry(key: "troegs nugget nectar", label: "Troegs Nugget Nectar", category: .draftBeer, abv: 7.5),
    BrandEntry(key: "troegs sunshine pils", label: "Troegs Sunshine Pils", category: .draftBeer, abv: 4.5),
    BrandEntry(key: "revolution anti-hero", label: "Revolution Anti-Hero", category: .draftBeer, abv: 6.7),
    BrandEntry(key: "elysian contact haze", label: "Elysian Contact Haze", category: .draftBeer, abv: 6.0),
    BrandEntry(key: "firestone walker 805", label: "Firestone Walker 805", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "firestone walker dba", label: "Firestone Walker DBA", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "oskar blues old chub", label: "Oskar Blues Old Chub", category: .draftBeer, abv: 8.0),
    BrandEntry(key: "rogue hazelnut brown", label: "Rogue Hazelnut Brown", category: .draftBeer, abv: 6.2),
    BrandEntry(key: "dogfish head namaste", label: "Dogfish Head Namaste", category: .draftBeer, abv: 4.8),
    BrandEntry(key: "oskar blues ten fidy", label: "Oskar Blues Ten FIDY", category: .draftBeer, abv: 10.5),
    BrandEntry(key: "fulton lonely blonde", label: "Fulton Lonely Blonde", category: .draftBeer, abv: 4.8),
    BrandEntry(key: "revolution fist city", label: "Revolution Fist City", category: .draftBeer, abv: 5.5),
    BrandEntry(key: "saint arnold art car", label: "Saint Arnold Art Car", category: .draftBeer, abv: 6.0),
    BrandEntry(key: "real ale fireman's 4", label: "Real Ale Fireman's 4", category: .draftBeer, abv: 5.1),
    BrandEntry(key: "community mosaic ipa", label: "Community Mosaic IPA", category: .draftBeer, abv: 7.5),
    BrandEntry(key: "georgetown bodhizafa", label: "Georgetown Bodhizafa", category: .draftBeer, abv: 6.9),
    BrandEntry(key: "breakside wanderlust", label: "Breakside Wanderlust", category: .draftBeer, abv: 6.2),
    BrandEntry(key: "10 barrel apocalypse", label: "10 Barrel Apocalypse", category: .draftBeer, abv: 6.8),
    BrandEntry(key: "epic big bad baptist", label: "Epic Big Bad Baptist", category: .bottledBeer, abv: 11.5),
    BrandEntry(key: "paulaner hefe-weizen", label: "Paulaner Hefe-Weizen", category: .draftBeer, abv: 5.5),
    BrandEntry(key: "paulaner oktoberfest", label: "Paulaner Oktoberfest", category: .draftBeer, abv: 6.0),
    BrandEntry(key: "white claw refresher", label: "White Claw Refresher", category: .seltzer, abv: 5.0),
    BrandEntry(key: "topo chico margarita", label: "Topo Chico Margarita", category: .seltzer, abv: 4.7),
    BrandEntry(key: "twisted tea original", label: "Twisted Tea Original", category: .seltzer, abv: 5.0),
    BrandEntry(key: "strongbow gold apple", label: "Strongbow Gold Apple", category: .cider, abv: 5.0),
    BrandEntry(key: "budweiser select 55", label: "Budweiser Select 55", category: .bottledBeer, abv: 2.4),
    BrandEntry(key: "michelob ultra zero", label: "Michelob Ultra Zero", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "michelob amber bock", label: "Michelob Amber Bock", category: .bottledBeer, abv: 5.2),
    BrandEntry(key: "corona hard seltzer", label: "Corona Hard Seltzer", category: .seltzer, abv: 4.5),
    BrandEntry(key: "founders solid gold", label: "Founders Solid Gold", category: .draftBeer, abv: 4.5),
    BrandEntry(key: "sam adams cold snap", label: "Sam Adams Cold Snap", category: .bottledBeer, abv: 5.3),
    BrandEntry(key: "ithaca flower power", label: "Ithaca Flower Power", category: .draftBeer, abv: 7.5),
    BrandEntry(key: "southern tier 2xipa", label: "Southern Tier 2XIPA", category: .draftBeer, abv: 8.0),
    BrandEntry(key: "cigar city jai alai", label: "Cigar City Jai Alai", category: .draftBeer, abv: 7.5),
    BrandEntry(key: "karbach love street", label: "Karbach Love Street", category: .draftBeer, abv: 4.9),
    BrandEntry(key: "simply spiked peach", label: "Simply Spiked Peach", category: .seltzer, abv: 5.0),
    BrandEntry(key: "trillium fort point", label: "Trillium Fort Point", category: .draftBeer, abv: 6.6),
    BrandEntry(key: "montauk wave chaser", label: "Montauk Wave Chaser", category: .draftBeer, abv: 6.0),
    BrandEntry(key: "stone delicious ipa", label: "Stone Delicious IPA", category: .draftBeer, abv: 7.7),
    BrandEntry(key: "karl strauss mosaic", label: "Karl Strauss Mosaic", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "new glarus moon man", label: "New Glarus Moon Man", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "live oak hefeweizen", label: "Live Oak Hefeweizen", category: .draftBeer, abv: 5.3),
    BrandEntry(key: "ninkasi tricerahops", label: "Ninkasi Tricerahops", category: .draftBeer, abv: 8.0),
    BrandEntry(key: "reuben's crikey ipa", label: "Reuben's Crikey IPA", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "ska modus hoperandi", label: "Ska Modus Hoperandi", category: .draftBeer, abv: 6.8),
    BrandEntry(key: "lindemans framboise", label: "Lindemans Framboise", category: .bottledBeer, abv: 2.5),
    BrandEntry(key: "brewdog elvis juice", label: "BrewDog Elvis Juice", category: .draftBeer, abv: 6.5),
    BrandEntry(key: "truly vodka seltzer", label: "Truly Vodka Seltzer", category: .seltzer, abv: 5.0),
    BrandEntry(key: "bud light platinum", label: "Bud Light Platinum", category: .bottledBeer, abv: 6.0),
    BrandEntry(key: "bell's two hearted", label: "Bell's Two Hearted", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "elysian space dust", label: "Elysian Space Dust", category: .draftBeer, abv: 8.2),
    BrandEntry(key: "athletic free wave", label: "Athletic Free Wave", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "victory prima pils", label: "Victory Prima Pils", category: .draftBeer, abv: 5.3),
    BrandEntry(key: "avery white rascal", label: "Avery White Rascal", category: .draftBeer, abv: 5.6),
    BrandEntry(key: "anchor liberty ale", label: "Anchor Liberty Ale", category: .draftBeer, abv: 5.9),
    BrandEntry(key: "angry orchard rose", label: "Angry Orchard Rose", category: .cider, abv: 5.5),
    BrandEntry(key: "oskar blues pinner", label: "Oskar Blues Pinner", category: .draftBeer, abv: 4.9),
    BrandEntry(key: "foothills jade ipa", label: "Foothills Jade IPA", category: .draftBeer, abv: 6.3),
    BrandEntry(key: "new realm hoplanta", label: "New Realm Hoplanta", category: .draftBeer, abv: 6.5),
    BrandEntry(key: "wiseacre tiny bomb", label: "Wiseacre Tiny Bomb", category: .draftBeer, abv: 4.5),
    BrandEntry(key: "fort george vortex", label: "Fort George Vortex", category: .draftBeer, abv: 7.7),
    BrandEntry(key: "beck's oktoberfest", label: "Beck's Oktoberfest", category: .bottledBeer, abv: 5.9),
    BrandEntry(key: "spaten oktoberfest", label: "Spaten Oktoberfest", category: .draftBeer, abv: 5.9),
    BrandEntry(key: "delirium nocturnum", label: "Delirium Nocturnum", category: .bottledBeer, abv: 8.5),
    BrandEntry(key: "carlsberg elephant", label: "Carlsberg Elephant", category: .bottledBeer, abv: 7.2),
    BrandEntry(key: "smirnoff ice smash", label: "Smirnoff Ice Smash", category: .seltzer, abv: 8.0),
    BrandEntry(key: "willie's superbrew", label: "Willie's Superbrew", category: .seltzer, abv: 5.0),
    BrandEntry(key: "golden state cider", label: "Golden State Cider", category: .cider, abv: 6.5),
    BrandEntry(key: "nicolas feuillatte", label: "Nicolas Feuillatte", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "bud light seltzer", label: "Bud Light Seltzer", category: .seltzer, abv: 5.0),
    BrandEntry(key: "michelob ultra na", label: "Michelob Ultra NA", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "pabst blue ribbon", label: "Pabst Blue Ribbon", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "genesee cream ale", label: "Genesee Cream Ale", category: .bottledBeer, abv: 5.1),
    BrandEntry(key: "stella artois 0.0", label: "Stella Artois 0.0", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "high noon tequila", label: "High Noon Tequila", category: .seltzer, abv: 4.5),
    BrandEntry(key: "twisted tea light", label: "Twisted Tea Light", category: .seltzer, abv: 4.0),
    BrandEntry(key: "athletic run wild", label: "Athletic Run Wild", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "la marca prosecco", label: "La Marca Prosecco", category: .wineGlass, abv: 11.0),
    BrandEntry(key: "national bohemian", label: "National Bohemian", category: .bottledBeer, abv: 4.3),
    BrandEntry(key: "st. pauli girl na", label: "St. Pauli Girl NA", category: .nonAlcoholic, abv: 0.5),
    BrandEntry(key: "lagunitas daytime", label: "Lagunitas Daytime", category: .draftBeer, abv: 4.0),
    BrandEntry(key: "new belgium mural", label: "New Belgium Mural", category: .draftBeer, abv: 4.9),
    BrandEntry(key: "cigar city maduro", label: "Cigar City Maduro", category: .draftBeer, abv: 5.5),
    BrandEntry(key: "odell 90 shilling", label: "Odell 90 Shilling", category: .draftBeer, abv: 5.3),
    BrandEntry(key: "abita purple haze", label: "Abita Purple Haze", category: .bottledBeer, abv: 4.2),
    BrandEntry(key: "great divide yeti", label: "Great Divide Yeti", category: .draftBeer, abv: 9.5),
    BrandEntry(key: "widmer hefeweizen", label: "Widmer Hefeweizen", category: .draftBeer, abv: 4.9),
    BrandEntry(key: "karbach hopadillo", label: "Karbach Hopadillo", category: .draftBeer, abv: 6.6),
    BrandEntry(key: "austin eastciders", label: "Austin Eastciders", category: .cider, abv: 5.0),
    BrandEntry(key: "surfside lemonade", label: "Surfside Lemonade", category: .seltzer, abv: 4.5),
    BrandEntry(key: "seagram's escapes", label: "Seagram's Escapes", category: .seltzer, abv: 3.2),
    BrandEntry(key: "not your father's", label: "Not Your Father's", category: .seltzer, abv: 5.9),
    BrandEntry(key: "tree house julius", label: "Tree House Julius", category: .draftBeer, abv: 6.8),
    BrandEntry(key: "lagunitas maximus", label: "Lagunitas Maximus", category: .draftBeer, abv: 8.2),
    BrandEntry(key: "paulaner salvator", label: "Paulaner Salvator", category: .draftBeer, abv: 7.9),
    BrandEntry(key: "brewdog hazy jane", label: "BrewDog Hazy Jane", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "country time hard", label: "Country Time Hard", category: .seltzer, abv: 5.0),
    BrandEntry(key: "downeast original", label: "Downeast Original", category: .cider, abv: 5.1),
    BrandEntry(key: "julian hard cider", label: "Julian Hard Cider", category: .cider, abv: 6.9),
    BrandEntry(key: "stella rosa black", label: "Stella Rosa Black", category: .wineGlass, abv: 5.5),
    BrandEntry(key: "budweiser select", label: "Budweiser Select", category: .bottledBeer, abv: 4.3),
    BrandEntry(key: "miller high life", label: "Miller High Life", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "guinness draught", label: "Guinness Draught", category: .draftBeer, abv: 4.2),
    BrandEntry(key: "white claw surge", label: "White Claw Surge", category: .seltzer, abv: 8.0),
    BrandEntry(key: "yuengling flight", label: "Yuengling Flight", category: .bottledBeer, abv: 4.2),
    BrandEntry(key: "olde english 800", label: "Olde English 800", category: .bottledBeer, abv: 7.5),
    BrandEntry(key: "estrella jalisco", label: "Estrella Jalisco", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "delirium tremens", label: "Delirium Tremens", category: .bottledBeer, abv: 8.5),
    BrandEntry(key: "kronenbourg 1664", label: "Kronenbourg 1664", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "sixpoint bengali", label: "Sixpoint Bengali", category: .draftBeer, abv: 6.5),
    BrandEntry(key: "victory hopdevil", label: "Victory HopDevil", category: .draftBeer, abv: 6.7),
    BrandEntry(key: "goose island ipa", label: "Goose Island IPA", category: .draftBeer, abv: 5.9),
    BrandEntry(key: "goose island 312", label: "Goose Island 312", category: .draftBeer, abv: 4.2),
    BrandEntry(key: "boulevard tank 7", label: "Boulevard Tank 7", category: .bottledBeer, abv: 8.5),
    BrandEntry(key: "johnny appleseed", label: "Johnny Appleseed", category: .cider, abv: 5.5),
    BrandEntry(key: "smirnoff seltzer", label: "Smirnoff Seltzer", category: .seltzer, abv: 4.5),
    BrandEntry(key: "best day brewing", label: "Best Day Brewing", category: .nonAlcoholic, abv: 0.5),
    BrandEntry(key: "other half green", label: "Other Half Green", category: .draftBeer, abv: 6.5),
    BrandEntry(key: "maine beer lunch", label: "Maine Beer Lunch", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "sloop juice bomb", label: "Sloop Juice Bomb", category: .draftBeer, abv: 6.5),
    BrandEntry(key: "coronado brewing", label: "Coronado Brewing", category: .draftBeer, abv: 6.0),
    BrandEntry(key: "kern river citra", label: "Kern River Citra", category: .draftBeer, abv: 8.0),
    BrandEntry(key: "spaten optimator", label: "Spaten Optimator", category: .draftBeer, abv: 7.6),
    BrandEntry(key: "schneider weisse", label: "Schneider Weisse", category: .draftBeer, abv: 5.4),
    BrandEntry(key: "warsteiner fresh", label: "Warsteiner Fresh", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "westmalle dubbel", label: "Westmalle Dubbel", category: .bottledBeer, abv: 7.0),
    BrandEntry(key: "westmalle tripel", label: "Westmalle Tripel", category: .bottledBeer, abv: 9.5),
    BrandEntry(key: "tripel karmeliet", label: "Tripel Karmeliet", category: .bottledBeer, abv: 8.4),
    BrandEntry(key: "hoegaarden rosee", label: "Hoegaarden Rosee", category: .bottledBeer, abv: 3.0),
    BrandEntry(key: "old speckled hen", label: "Old Speckled Hen", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "brewdog punk ipa", label: "BrewDog Punk IPA", category: .draftBeer, abv: 5.4),
    BrandEntry(key: "athletic all out", label: "Athletic All Out", category: .nonAlcoholic, abv: 0.3),
    BrandEntry(key: "domaine carneros", label: "Domaine Carneros", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "yuengling light", label: "Yuengling Light", category: .bottledBeer, abv: 3.8),
    BrandEntry(key: "modelo especial", label: "Modelo Especial", category: .bottledBeer, abv: 4.4),
    BrandEntry(key: "dos equis amber", label: "Dos Equis Amber", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "dos equis lager", label: "Dos Equis Lager", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "pilsner urquell", label: "Pilsner Urquell", category: .bottledBeer, abv: 4.4),
    BrandEntry(key: "yuengling lager", label: "Yuengling Lager", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "corona familiar", label: "Corona Familiar", category: .bottledBeer, abv: 4.8),
    BrandEntry(key: "corona refresca", label: "Corona Refresca", category: .seltzer, abv: 4.5),
    BrandEntry(key: "tecate titanium", label: "Tecate Titanium", category: .bottledBeer, abv: 7.5),
    BrandEntry(key: "bitburger drive", label: "Bitburger Drive", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "guinness blonde", label: "Guinness Blonde", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "sapporo premium", label: "Sapporo Premium", category: .bottledBeer, abv: 4.9),
    BrandEntry(key: "asahi super dry", label: "Asahi Super Dry", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "brooklyn summer", label: "Brooklyn Summer", category: .draftBeer, abv: 4.6),
    BrandEntry(key: "founders porter", label: "Founders Porter", category: .draftBeer, abv: 6.5),
    BrandEntry(key: "lagunitas sucks", label: "Lagunitas Sucks", category: .draftBeer, abv: 7.6),
    BrandEntry(key: "dale's pale ale", label: "Dale's Pale Ale", category: .bottledBeer, abv: 6.5),
    BrandEntry(key: "pliny the elder", label: "Pliny the Elder", category: .draftBeer, abv: 8.0),
    BrandEntry(key: "woodchuck amber", label: "Woodchuck Amber", category: .cider, abv: 5.0),
    BrandEntry(key: "schilling cider", label: "Schilling Cider", category: .cider, abv: 6.5),
    BrandEntry(key: "lipton hard tea", label: "Lipton Hard Tea", category: .seltzer, abv: 5.0),
    BrandEntry(key: "surreal brewing", label: "Surreal Brewing", category: .nonAlcoholic, abv: 0.2),
    BrandEntry(key: "hoppy refresher", label: "Hoppy Refresher", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "martini & rossi", label: "Martini & Rossi", category: .wineGlass, abv: 7.5),
    BrandEntry(key: "barefoot bubbly", label: "Barefoot Bubbly", category: .wineGlass, abv: 10.5),
    BrandEntry(key: "stone buenaveza", label: "Stone Buenaveza", category: .draftBeer, abv: 4.7),
    BrandEntry(key: "surly overrated", label: "Surly Overrated", category: .draftBeer, abv: 7.3),
    BrandEntry(key: "abita andygator", label: "Abita Andygator", category: .bottledBeer, abv: 8.0),
    BrandEntry(key: "maisel's weisse", label: "Maisel's Weisse", category: .draftBeer, abv: 5.4),
    BrandEntry(key: "lindemans kriek", label: "Lindemans Kriek", category: .bottledBeer, abv: 3.5),
    BrandEntry(key: "victoria bitter", label: "Victoria Bitter", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "truly margarita", label: "Truly Margarita", category: .seltzer, abv: 5.0),
    BrandEntry(key: "long drink zero", label: "Long Drink Zero", category: .seltzer, abv: 5.0),
    BrandEntry(key: "piper-heidsieck", label: "Piper-Heidsieck", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "laurent-perrier", label: "Laurent-Perrier", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "roederer estate", label: "Roederer Estate", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "bud light lime", label: "Bud Light Lime", category: .bottledBeer, abv: 4.2),
    BrandEntry(key: "budweiser zero", label: "Budweiser Zero", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "michelob ultra", label: "Michelob Ultra", category: .bottledBeer, abv: 4.2),
    BrandEntry(key: "keystone light", label: "Keystone Light", category: .bottledBeer, abv: 4.1),
    BrandEntry(key: "corona premier", label: "Corona Premier", category: .bottledBeer, abv: 4.0),
    BrandEntry(key: "heineken light", label: "Heineken Light", category: .bottledBeer, abv: 3.3),
    BrandEntry(key: "kona longboard", label: "Kona Longboard", category: .draftBeer, abv: 4.6),
    BrandEntry(key: "allagash white", label: "Allagash White", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "downeast cider", label: "Downeast Cider", category: .cider, abv: 5.1),
    BrandEntry(key: "zonin prosecco", label: "Zonin Prosecco", category: .wineGlass, abv: 11.0),
    BrandEntry(key: "modelo chelada", label: "Modelo Chelada", category: .bottledBeer, abv: 3.5),
    BrandEntry(key: "st. pauli girl", label: "St. Pauli Girl", category: .bottledBeer, abv: 4.9),
    BrandEntry(key: "brooklyn lager", label: "Brooklyn Lager", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "lagunitas ipna", label: "Lagunitas IPNA", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "rogue dead guy", label: "Rogue Dead Guy", category: .draftBeer, abv: 6.8),
    BrandEntry(key: "sweetwater 420", label: "SweetWater 420", category: .draftBeer, abv: 5.7),
    BrandEntry(key: "portland cider", label: "Portland Cider", category: .cider, abv: 5.5),
    BrandEntry(key: "truly iced tea", label: "Truly Iced Tea", category: .seltzer, abv: 5.0),
    BrandEntry(key: "crook & marker", label: "Crook & Marker", category: .seltzer, abv: 4.5),
    BrandEntry(key: "o'doul's amber", label: "O'Doul's Amber", category: .nonAlcoholic, abv: 0.4),
    BrandEntry(key: "veuve clicquot", label: "Veuve Clicquot", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "verdi spumante", label: "Verdi Spumante", category: .wineGlass, abv: 5.0),
    BrandEntry(key: "bell's hopslam", label: "Bell's Hopslam", category: .draftBeer, abv: 10.0),
    BrandEntry(key: "stone enjoy by", label: "Stone Enjoy By", category: .draftBeer, abv: 9.4),
    BrandEntry(key: "half acre pony", label: "Half Acre Pony", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "sweetwater ipa", label: "SweetWater IPA", category: .draftBeer, abv: 6.3),
    BrandEntry(key: "abita turbodog", label: "Abita Turbodog", category: .bottledBeer, abv: 5.6),
    BrandEntry(key: "deep ellum ipa", label: "Deep Ellum IPA", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "fort point ksa", label: "Fort Point KSA", category: .draftBeer, abv: 4.5),
    BrandEntry(key: "pfriem pilsner", label: "pFriem Pilsner", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "uinta hop nosh", label: "Uinta Hop Nosh", category: .draftBeer, abv: 7.3),
    BrandEntry(key: "hacker-pschorr", label: "Hacker-Pschorr", category: .draftBeer, abv: 5.5),
    BrandEntry(key: "krombacher 0.0", label: "Krombacher 0.0", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "vizzy lemonade", label: "Vizzy Lemonade", category: .seltzer, abv: 5.0),
    BrandEntry(key: "coors banquet", label: "Coors Banquet", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "natural light", label: "Natural Light", category: .bottledBeer, abv: 4.2),
    BrandEntry(key: "old milwaukee", label: "Old Milwaukee", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "stella artois", label: "Stella Artois", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "guinness zero", label: "Guinness Zero", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "sierra nevada", label: "Sierra Nevada", category: .draftBeer, abv: 5.6),
    BrandEntry(key: "lagunitas ipa", label: "Lagunitas IPA", category: .draftBeer, abv: 6.2),
    BrandEntry(key: "bell's oberon", label: "Bell's Oberon", category: .draftBeer, abv: 5.8),
    BrandEntry(key: "voodoo ranger", label: "Voodoo Ranger", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "kona big wave", label: "Kona Big Wave", category: .draftBeer, abv: 4.4),
    BrandEntry(key: "weihenstephan", label: "Weihenstephan", category: .draftBeer, abv: 5.4),
    BrandEntry(key: "alaskan amber", label: "Alaskan Amber", category: .draftBeer, abv: 5.3),
    BrandEntry(key: "surly axe man", label: "Surly Axe Man", category: .draftBeer, abv: 7.2),
    BrandEntry(key: "angry orchard", label: "Angry Orchard", category: .cider, abv: 5.0),
    BrandEntry(key: "white claw na", label: "White Claw NA", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "simply spiked", label: "Simply Spiked", category: .seltzer, abv: 5.0),
    BrandEntry(key: "genesee light", label: "Genesee Light", category: .bottledBeer, abv: 3.8),
    BrandEntry(key: "steel reserve", label: "Steel Reserve", category: .bottledBeer, abv: 8.1),
    BrandEntry(key: "birra moretti", label: "Birra Moretti", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "estrella damm", label: "Estrella Damm", category: .bottledBeer, abv: 5.4),
    BrandEntry(key: "kirin ichiban", label: "Kirin Ichiban", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "yards brawler", label: "Yards Brawler", category: .draftBeer, abv: 4.2),
    BrandEntry(key: "surly furious", label: "Surly Furious", category: .draftBeer, abv: 6.7),
    BrandEntry(key: "bell's porter", label: "Bell's Porter", category: .draftBeer, abv: 5.6),
    BrandEntry(key: "ace pineapple", label: "Ace Pineapple", category: .cider, abv: 5.0),
    BrandEntry(key: "seattle cider", label: "Seattle Cider", category: .cider, abv: 6.5),
    BrandEntry(key: "smith & forge", label: "Smith & Forge", category: .cider, abv: 6.0),
    BrandEntry(key: "mike's harder", label: "Mike's Harder", category: .seltzer, abv: 8.0),
    BrandEntry(key: "flying embers", label: "Flying Embers", category: .seltzer, abv: 5.0),
    BrandEntry(key: "segura viudas", label: "Segura Viudas", category: .wineGlass, abv: 11.5),
    BrandEntry(key: "noda hop drop", label: "NoDa Hop Drop", category: .draftBeer, abv: 7.2),
    BrandEntry(key: "alpine nelson", label: "Alpine Nelson", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "chimay triple", label: "Chimay Triple", category: .bottledBeer, abv: 8.0),
    BrandEntry(key: "st. bernardus", label: "St. Bernardus", category: .bottledBeer, abv: 10.0),
    BrandEntry(key: "kasteel rouge", label: "Kasteel Rouge", category: .bottledBeer, abv: 8.0),
    BrandEntry(key: "medalla light", label: "Medalla Light", category: .bottledBeer, abv: 4.2),
    BrandEntry(key: "citizen cider", label: "Citizen Cider", category: .cider, abv: 6.5),
    BrandEntry(key: "perrier-jouet", label: "Perrier-Jouet", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "keystone ice", label: "Keystone Ice", category: .bottledBeer, abv: 5.9),
    BrandEntry(key: "rolling rock", label: "Rolling Rock", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "corona light", label: "Corona Light", category: .bottledBeer, abv: 4.0),
    BrandEntry(key: "corona extra", label: "Corona Extra", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "modelo negra", label: "Modelo Negra", category: .bottledBeer, abv: 5.4),
    BrandEntry(key: "heineken 0.0", label: "Heineken 0.0", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "amstel light", label: "Amstel Light", category: .bottledBeer, abv: 3.5),
    BrandEntry(key: "guinness 0.0", label: "Guinness 0.0", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "founders kbs", label: "Founders KBS", category: .draftBeer, abv: 12.0),
    BrandEntry(key: "franziskaner", label: "Franziskaner", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "mighty swell", label: "Mighty Swell", category: .seltzer, abv: 5.0),
    BrandEntry(key: "smirnoff ice", label: "Smirnoff Ice", category: .seltzer, abv: 4.5),
    BrandEntry(key: "narragansett", label: "Narragansett", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "tecate light", label: "Tecate Light", category: .bottledBeer, abv: 3.9),
    BrandEntry(key: "carta blanca", label: "Carta Blanca", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "samuel adams", label: "Samuel Adams", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "bell's amber", label: "Bell's Amber", category: .draftBeer, abv: 5.8),
    BrandEntry(key: "anchor steam", label: "Anchor Steam", category: .draftBeer, abv: 4.9),
    BrandEntry(key: "alesmith ipa", label: "AleSmith IPA", category: .draftBeer, abv: 7.3),
    BrandEntry(key: "stella cidre", label: "Stella Cidre", category: .cider, abv: 4.5),
    BrandEntry(key: "virtue cider", label: "Virtue Cider", category: .cider, abv: 6.8),
    BrandEntry(key: "original sin", label: "Original Sin", category: .cider, abv: 6.0),
    BrandEntry(key: "surfside tea", label: "Surfside Tea", category: .seltzer, abv: 4.5),
    BrandEntry(key: "arizona hard", label: "Arizona Hard", category: .seltzer, abv: 5.0),
    BrandEntry(key: "hairless dog", label: "Hairless Dog", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "dom perignon", label: "Dom Perignon", category: .wineGlass, abv: 12.5),
    BrandEntry(key: "drake's 1500", label: "Drake's 1500", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "boneyard rpm", label: "Boneyard RPM", category: .draftBeer, abv: 6.5),
    BrandEntry(key: "fremont lush", label: "Fremont Lush", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "rochefort 10", label: "Rochefort 10", category: .bottledBeer, abv: 11.3),
    BrandEntry(key: "gulden draak", label: "Gulden Draak", category: .bottledBeer, abv: 10.5),
    BrandEntry(key: "leffe blonde", label: "Leffe Blonde", category: .bottledBeer, abv: 6.6),
    BrandEntry(key: "fuller's esb", label: "Fuller's ESB", category: .draftBeer, abv: 5.9),
    BrandEntry(key: "london pride", label: "London Pride", category: .draftBeer, abv: 4.7),
    BrandEntry(key: "innis & gunn", label: "Innis & Gunn", category: .bottledBeer, abv: 6.6),
    BrandEntry(key: "sonoma cider", label: "Sonoma Cider", category: .cider, abv: 6.0),
    BrandEntry(key: "cinzano asti", label: "Cinzano Asti", category: .wineGlass, abv: 7.0),
    BrandEntry(key: "coors light", label: "Coors Light", category: .bottledBeer, abv: 4.2),
    BrandEntry(key: "miller lite", label: "Miller Lite", category: .bottledBeer, abv: 4.2),
    BrandEntry(key: "busch light", label: "Busch Light", category: .bottledBeer, abv: 4.1),
    BrandEntry(key: "natural ice", label: "Natural Ice", category: .bottledBeer, abv: 5.9),
    BrandEntry(key: "labatt blue", label: "Labatt Blue", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "corona cero", label: "Corona Cero", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "heineken na", label: "Heineken NA", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "beck's blue", label: "Beck's Blue", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "smithwick's", label: "Smithwick's", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "shiner bock", label: "Shiner Bock", category: .bottledBeer, abv: 4.4),
    BrandEntry(key: "spotted cow", label: "Spotted Cow", category: .draftBeer, abv: 4.8),
    BrandEntry(key: "twisted tea", label: "Twisted Tea", category: .seltzer, abv: 5.0),
    BrandEntry(key: "mike's hard", label: "Mike's Hard", category: .seltzer, abv: 5.0),
    BrandEntry(key: "cayman jack", label: "Cayman Jack", category: .seltzer, abv: 5.8),
    BrandEntry(key: "run wild na", label: "Run Wild NA", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "clausthaler", label: "Clausthaler", category: .nonAlcoholic, abv: 0.5),
    BrandEntry(key: "chimay blue", label: "Chimay Blue", category: .bottledBeer, abv: 9.0),
    BrandEntry(key: "boddingtons", label: "Boddingtons", category: .draftBeer, abv: 4.6),
    BrandEntry(key: "kronenbourg", label: "Kronenbourg", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "staropramen", label: "Staropramen", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "harpoon ipa", label: "Harpoon IPA", category: .draftBeer, abv: 5.9),
    BrandEntry(key: "harpoon ufo", label: "Harpoon UFO", category: .draftBeer, abv: 4.8),
    BrandEntry(key: "abita amber", label: "Abita Amber", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "truly punch", label: "Truly Punch", category: .seltzer, abv: 5.0),
    BrandEntry(key: "lime-a-rita", label: "Lime-A-Rita", category: .seltzer, abv: 8.0),
    BrandEntry(key: "summit saga", label: "Summit Saga", category: .draftBeer, abv: 6.4),
    BrandEntry(key: "rahr blonde", label: "Rahr Blonde", category: .draftBeer, abv: 4.9),
    BrandEntry(key: "celis white", label: "Celis White", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "dinkelacker", label: "Dinkelacker", category: .bottledBeer, abv: 5.1),
    BrandEntry(key: "flensburger", label: "Flensburger", category: .bottledBeer, abv: 4.8),
    BrandEntry(key: "rochefort 8", label: "Rochefort 8", category: .bottledBeer, abv: 9.2),
    BrandEntry(key: "rochefort 6", label: "Rochefort 6", category: .bottledBeer, abv: 7.5),
    BrandEntry(key: "leffe brune", label: "Leffe Brune", category: .bottledBeer, abv: 6.5),
    BrandEntry(key: "two robbers", label: "Two Robbers", category: .seltzer, abv: 5.0),
    BrandEntry(key: "vander mill", label: "Vander Mill", category: .cider, abv: 6.8),
    BrandEntry(key: "villa sandi", label: "Villa Sandi", category: .wineGlass, abv: 11.0),
    BrandEntry(key: "schramsberg", label: "Schramsberg", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "stella rosa", label: "Stella Rosa", category: .wineGlass, abv: 5.5),
    BrandEntry(key: "red stripe", label: "Red Stripe", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "presidente", label: "Presidente", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "mango cart", label: "Mango Cart", category: .draftBeer, abv: 4.0),
    BrandEntry(key: "warsteiner", label: "Warsteiner", category: .draftBeer, abv: 4.8),
    BrandEntry(key: "white claw", label: "White Claw", category: .seltzer, abv: 5.0),
    BrandEntry(key: "long drink", label: "Long Drink", category: .seltzer, abv: 5.5),
    BrandEntry(key: "coors edge", label: "Coors Edge", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "modelo oro", label: "Modelo Oro", category: .bottledBeer, abv: 4.0),
    BrandEntry(key: "krombacher", label: "Krombacher", category: .draftBeer, abv: 4.8),
    BrandEntry(key: "radeberger", label: "Radeberger", category: .draftBeer, abv: 4.8),
    BrandEntry(key: "augustiner", label: "Augustiner", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "kostritzer", label: "Kostritzer", category: .draftBeer, abv: 4.8),
    BrandEntry(key: "hoegaarden", label: "Hoegaarden", category: .bottledBeer, abv: 4.9),
    BrandEntry(key: "la chouffe", label: "La Chouffe", category: .bottledBeer, abv: 8.0),
    BrandEntry(key: "grimbergen", label: "Grimbergen", category: .bottledBeer, abv: 6.7),
    BrandEntry(key: "peroni 0.0", label: "Peroni 0.0", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "san miguel", label: "San Miguel", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "1664 blanc", label: "1664 Blanc", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "tiger beer", label: "Tiger Beer", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "kingfisher", label: "Kingfisher", category: .bottledBeer, abv: 4.8),
    BrandEntry(key: "long trail", label: "Long Trail", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "new glarus", label: "New Glarus", category: .draftBeer, abv: 5.0),
    BrandEntry(key: "summit epa", label: "Summit EPA", category: .draftBeer, abv: 5.3),
    BrandEntry(key: "mckenzie's", label: "McKenzie's", category: .cider, abv: 5.0),
    BrandEntry(key: "kopparberg", label: "Kopparberg", category: .cider, abv: 4.0),
    BrandEntry(key: "boochcraft", label: "Boochcraft", category: .seltzer, abv: 7.0),
    BrandEntry(key: "chimay red", label: "Chimay Red", category: .bottledBeer, abv: 7.0),
    BrandEntry(key: "super bock", label: "Super Bock", category: .bottledBeer, abv: 5.2),
    BrandEntry(key: "steinlager", label: "Steinlager", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "owl's brew", label: "Owl's Brew", category: .seltzer, abv: 4.0),
    BrandEntry(key: "kombrewcha", label: "Kombrewcha", category: .seltzer, abv: 3.2),
    BrandEntry(key: "woodpecker", label: "Woodpecker", category: .cider, abv: 4.5),
    BrandEntry(key: "go brewing", label: "Go Brewing", category: .nonAlcoholic, abv: 0.5),
    BrandEntry(key: "la gioiosa", label: "La Gioiosa", category: .wineGlass, abv: 11.0),
    BrandEntry(key: "taittinger", label: "Taittinger", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "tosti asti", label: "Tosti Asti", category: .wineGlass, abv: 7.0),
    BrandEntry(key: "bud light", label: "Bud Light", category: .bottledBeer, abv: 4.2),
    BrandEntry(key: "budweiser", label: "Budweiser", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "miller 64", label: "Miller 64", category: .bottledBeer, abv: 2.8),
    BrandEntry(key: "busch ice", label: "Busch Ice", category: .bottledBeer, abv: 5.9),
    BrandEntry(key: "yuengling", label: "Yuengling", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "dos equis", label: "Dos Equis", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "newcastle", label: "Newcastle", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "lagunitas", label: "Lagunitas", category: .draftBeer, abv: 6.2),
    BrandEntry(key: "stone ipa", label: "Stone IPA", category: .draftBeer, abv: 6.9),
    BrandEntry(key: "blue moon", label: "Blue Moon", category: .draftBeer, abv: 5.4),
    BrandEntry(key: "strongbow", label: "Strongbow", category: .cider, abv: 5.0),
    BrandEntry(key: "woodchuck", label: "Woodchuck", category: .cider, abv: 5.0),
    BrandEntry(key: "bold rock", label: "Bold Rock", category: .cider, abv: 4.7),
    BrandEntry(key: "high noon", label: "High Noon", category: .seltzer, abv: 4.5),
    BrandEntry(key: "bon & viv", label: "Bon & Viv", category: .seltzer, abv: 4.5),
    BrandEntry(key: "freixenet", label: "Freixenet", category: .wineGlass, abv: 11.5),
    BrandEntry(key: "lone star", label: "Lone Star", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "natty boh", label: "Natty Boh", category: .bottledBeer, abv: 4.3),
    BrandEntry(key: "iron city", label: "Iron City", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "lionshead", label: "Lionshead", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "bitburger", label: "Bitburger", category: .draftBeer, abv: 4.8),
    BrandEntry(key: "cruzcampo", label: "Cruzcampo", category: .bottledBeer, abv: 4.8),
    BrandEntry(key: "carlsberg", label: "Carlsberg", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "sam adams", label: "Sam Adams", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "magic hat", label: "Magic Hat", category: .draftBeer, abv: 5.1),
    BrandEntry(key: "odell ipa", label: "Odell IPA", category: .draftBeer, abv: 7.0),
    BrandEntry(key: "ace cider", label: "Ace Cider", category: .cider, abv: 5.0),
    BrandEntry(key: "four loko", label: "Four Loko", category: .seltzer, abv: 14.0),
    BrandEntry(key: "happy dad", label: "Happy Dad", category: .seltzer, abv: 5.0),
    BrandEntry(key: "juneshine", label: "JuneShine", category: .seltzer, abv: 6.0),
    BrandEntry(key: "wellbeing", label: "Wellbeing", category: .nonAlcoholic, abv: 0.4),
    BrandEntry(key: "ballatore", label: "Ballatore", category: .wineGlass, abv: 6.0),
    BrandEntry(key: "avery ipa", label: "Avery IPA", category: .draftBeer, abv: 6.5),
    BrandEntry(key: "lowenbrau", label: "Lowenbrau", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "aventinus", label: "Aventinus", category: .draftBeer, abv: 8.2),
    BrandEntry(key: "reissdorf", label: "Reissdorf", category: .draftBeer, abv: 4.8),
    BrandEntry(key: "westmalle", label: "Westmalle", category: .bottledBeer, abv: 9.5),
    BrandEntry(key: "rochefort", label: "Rochefort", category: .bottledBeer, abv: 9.2),
    BrandEntry(key: "maredsous", label: "Maredsous", category: .bottledBeer, abv: 8.0),
    BrandEntry(key: "rodenbach", label: "Rodenbach", category: .bottledBeer, abv: 5.2),
    BrandEntry(key: "hobgoblin", label: "Hobgoblin", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "tennent's", label: "Tennent's", category: .draftBeer, abv: 4.0),
    BrandEntry(key: "red horse", label: "Red Horse", category: .bottledBeer, abv: 6.9),
    BrandEntry(key: "taj mahal", label: "Taj Mahal", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "ace joker", label: "Ace Joker", category: .cider, abv: 6.9),
    BrandEntry(key: "finnriver", label: "Finnriver", category: .cider, abv: 6.5),
    BrandEntry(key: "hornsby's", label: "Hornsby's", category: .cider, abv: 6.0),
    BrandEntry(key: "free damm", label: "Free Damm", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "two roots", label: "Two Roots", category: .nonAlcoholic, abv: 0.5),
    BrandEntry(key: "bollinger", label: "Bollinger", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "pol roger", label: "Pol Roger", category: .wineGlass, abv: 12.5),
    BrandEntry(key: "bud zero", label: "Bud Zero", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "pacifico", label: "Pacifico", category: .bottledBeer, abv: 4.4),
    BrandEntry(key: "victoria", label: "Victoria", category: .bottledBeer, abv: 4.0),
    BrandEntry(key: "heineken", label: "Heineken", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "foster's", label: "Foster's", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "tsingtao", label: "Tsingtao", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "guinness", label: "Guinness", category: .draftBeer, abv: 4.2),
    BrandEntry(key: "founders", label: "Founders", category: .draftBeer, abv: 5.5),
    BrandEntry(key: "fat tire", label: "Fat Tire", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "paulaner", label: "Paulaner", category: .draftBeer, abv: 5.5),
    BrandEntry(key: "downeast", label: "Downeast", category: .cider, abv: 5.1),
    BrandEntry(key: "surfside", label: "Surfside", category: .seltzer, abv: 4.5),
    BrandEntry(key: "carbliss", label: "Carbliss", category: .seltzer, abv: 5.0),
    BrandEntry(key: "cutwater", label: "Cutwater", category: .seltzer, abv: 7.0),
    BrandEntry(key: "athletic", label: "Athletic", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "o'doul's", label: "O'Doul's", category: .nonAlcoholic, abv: 0.0),
    BrandEntry(key: "michelob", label: "Michelob", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "keystone", label: "Keystone", category: .bottledBeer, abv: 4.4),
    BrandEntry(key: "mickey's", label: "Mickey's", category: .bottledBeer, abv: 5.6),
    BrandEntry(key: "erdinger", label: "Erdinger", category: .draftBeer, abv: 5.3),
    BrandEntry(key: "affligem", label: "Affligem", category: .bottledBeer, abv: 6.8),
    BrandEntry(key: "kilkenny", label: "Kilkenny", category: .draftBeer, abv: 4.3),
    BrandEntry(key: "murphy's", label: "Murphy's", category: .draftBeer, abv: 4.0),
    BrandEntry(key: "menabrea", label: "Menabrea", category: .bottledBeer, abv: 4.8),
    BrandEntry(key: "alhambra", label: "Alhambra", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "ommegang", label: "Ommegang", category: .bottledBeer, abv: 6.5),
    BrandEntry(key: "schlafly", label: "Schlafly", category: .draftBeer, abv: 4.5),
    BrandEntry(key: "somersby", label: "Somersby", category: .cider, abv: 4.5),
    BrandEntry(key: "loverboy", label: "Loverboy", category: .seltzer, abv: 4.2),
    BrandEntry(key: "hoop tea", label: "Hoop Tea", category: .seltzer, abv: 4.0),
    BrandEntry(key: "big drop", label: "Big Drop", category: .nonAlcoholic, abv: 0.5),
    BrandEntry(key: "mionetto", label: "Mionetto", category: .wineGlass, abv: 11.0),
    BrandEntry(key: "codorniu", label: "Codorniu", category: .wineGlass, abv: 11.5),
    BrandEntry(key: "schlitz", label: "Schlitz", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "sapporo", label: "Sapporo", category: .bottledBeer, abv: 4.9),
    BrandEntry(key: "genesee", label: "Genesee", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "rainier", label: "Rainier", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "olympia", label: "Olympia", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "colt 45", label: "Colt 45", category: .bottledBeer, abv: 5.6),
    BrandEntry(key: "montejo", label: "Montejo", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "hofbrau", label: "Hofbrau", category: .draftBeer, abv: 5.1),
    BrandEntry(key: "ayinger", label: "Ayinger", category: .draftBeer, abv: 5.1),
    BrandEntry(key: "jupiler", label: "Jupiler", category: .bottledBeer, abv: 5.2),
    BrandEntry(key: "beamish", label: "Beamish", category: .draftBeer, abv: 4.1),
    BrandEntry(key: "moretti", label: "Moretti", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "ichnusa", label: "Ichnusa", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "grolsch", label: "Grolsch", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "baltika", label: "Baltika", category: .bottledBeer, abv: 5.6),
    BrandEntry(key: "beerlao", label: "Beerlao", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "bintang", label: "Bintang", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "saranac", label: "Saranac", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "2 towns", label: "2 Towns", category: .cider, abv: 6.0),
    BrandEntry(key: "crispin", label: "Crispin", category: .cider, abv: 5.0),
    BrandEntry(key: "magners", label: "Magners", category: .cider, abv: 4.5),
    BrandEntry(key: "bulmers", label: "Bulmers", category: .cider, abv: 4.5),
    BrandEntry(key: "blake's", label: "Blake's", category: .cider, abv: 6.5),
    BrandEntry(key: "wyder's", label: "Wyder's", category: .cider, abv: 5.0),
    BrandEntry(key: "beatbox", label: "BeatBox", category: .seltzer, abv: 11.1),
    BrandEntry(key: "partake", label: "Partake", category: .nonAlcoholic, abv: 0.3),
    BrandEntry(key: "chandon", label: "Chandon", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "ruffino", label: "Ruffino", category: .wineGlass, abv: 11.0),
    BrandEntry(key: "riunite", label: "Riunite", category: .wineGlass, abv: 8.0),
    BrandEntry(key: "wycliff", label: "Wycliff", category: .wineGlass, abv: 11.0),
    BrandEntry(key: "j roget", label: "J Roget", category: .wineGlass, abv: 11.0),
    BrandEntry(key: "rothaus", label: "Rothaus", category: .draftBeer, abv: 5.1),
    BrandEntry(key: "quilmes", label: "Quilmes", category: .bottledBeer, abv: 4.9),
    BrandEntry(key: "poretti", label: "Poretti", category: .bottledBeer, abv: 4.8),
    BrandEntry(key: "bottega", label: "Bottega", category: .wineGlass, abv: 11.0),
    BrandEntry(key: "hamm's", label: "Hamm's", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "corona", label: "Corona", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "modelo", label: "Modelo", category: .bottledBeer, abv: 4.4),
    BrandEntry(key: "tecate", label: "Tecate", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "dos xx", label: "Dos XX", category: .bottledBeer, abv: 4.5),
    BrandEntry(key: "peroni", label: "Peroni", category: .bottledBeer, abv: 5.1),
    BrandEntry(key: "beck's", label: "Beck's", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "spaten", label: "Spaten", category: .draftBeer, abv: 5.2),
    BrandEntry(key: "korbel", label: "Korbel", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "miller", label: "Miller", category: .bottledBeer, abv: 4.6),
    BrandEntry(key: "straub", label: "Straub", category: .bottledBeer, abv: 4.4),
    BrandEntry(key: "shiner", label: "Shiner", category: .bottledBeer, abv: 4.4),
    BrandEntry(key: "chimay", label: "Chimay", category: .bottledBeer, abv: 7.0),
    BrandEntry(key: "amstel", label: "Amstel", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "tuborg", label: "Tuborg", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "budvar", label: "Budvar", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "zywiec", label: "Zywiec", category: .bottledBeer, abv: 5.6),
    BrandEntry(key: "tyskie", label: "Tyskie", category: .bottledBeer, abv: 5.5),
    BrandEntry(key: "singha", label: "Singha", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "troegs", label: "Troegs", category: .draftBeer, abv: 5.5),
    BrandEntry(key: "redd's", label: "Redd's", category: .seltzer, abv: 5.0),
    BrandEntry(key: "cook's", label: "Cook's", category: .wineGlass, abv: 11.0),
    BrandEntry(key: "gaffel", label: "Gaffel", category: .draftBeer, abv: 4.8),
    BrandEntry(key: "piraat", label: "Piraat", category: .bottledBeer, abv: 10.5),
    BrandEntry(key: "vedett", label: "Vedett", category: .bottledBeer, abv: 5.2),
    BrandEntry(key: "brahma", label: "Brahma", category: .bottledBeer, abv: 4.8),
    BrandEntry(key: "sagres", label: "Sagres", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "yebisu", label: "Yebisu", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "bravus", label: "Bravus", category: .nonAlcoholic, abv: 0.5),
    BrandEntry(key: "busch", label: "Busch", category: .bottledBeer, abv: 4.3),
    BrandEntry(key: "asahi", label: "Asahi", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "kirin", label: "Kirin", category: .bottledBeer, abv: 4.9),
    BrandEntry(key: "truly", label: "Truly", category: .seltzer, abv: 5.0),
    BrandEntry(key: "nutrl", label: "Nutrl", category: .seltzer, abv: 4.5),
    BrandEntry(key: "vizzy", label: "Vizzy", category: .seltzer, abv: 5.0),
    BrandEntry(key: "press", label: "Press", category: .seltzer, abv: 4.0),
    BrandEntry(key: "coors", label: "Coors", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "pabst", label: "Pabst", category: .bottledBeer, abv: 4.7),
    BrandEntry(key: "indio", label: "Indio", category: .bottledBeer, abv: 4.1),
    BrandEntry(key: "jever", label: "Jever", category: .draftBeer, abv: 4.9),
    BrandEntry(key: "duvel", label: "Duvel", category: .bottledBeer, abv: 8.5),
    BrandEntry(key: "leffe", label: "Leffe", category: .bottledBeer, abv: 6.6),
    BrandEntry(key: "orval", label: "Orval", category: .bottledBeer, abv: 6.2),
    BrandEntry(key: "mahou", label: "Mahou", category: .bottledBeer, abv: 5.5),
    BrandEntry(key: "kozel", label: "Kozel", category: .draftBeer, abv: 4.6),
    BrandEntry(key: "gruvi", label: "Gruvi", category: .nonAlcoholic, abv: 0.5),
    BrandEntry(key: "andre", label: "Andre", category: .wineGlass, abv: 10.5),
    BrandEntry(key: "poema", label: "Poema", category: .wineGlass, abv: 11.5),
    BrandEntry(key: "gruet", label: "Gruet", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "bass", label: "Bass", category: .bottledBeer, abv: 5.1),
    BrandEntry(key: "kwak", label: "Kwak", category: .bottledBeer, abv: 8.4),
    BrandEntry(key: "efes", label: "Efes", category: .bottledBeer, abv: 5.0),
    BrandEntry(key: "mumm", label: "Mumm", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "moet", label: "Moet", category: .wineGlass, abv: 12.0),
    BrandEntry(key: "pbr", label: "PBR", category: .bottledBeer, abv: 4.7),
]
