#!/usr/bin/env bash
# print_structure — regenerate docs/ProjectStructure.md from the real tree (§9 tooling).
# Run at the end of every phase (and after adding any script/source) so the structure doc
# can never drift from reality. Portable: no `tree`, no GNU-only `find -printf`.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/docs/ProjectStructure.md"
cd "$ROOT"

NOW="$(date -u '+%Y-%m-%d %H:%M UTC')"

# Sorted so parents precede children; two-space indent per depth; dirs get a trailing slash.
BODY="$(
  find . -mindepth 1 \
      \( -name '.git' -o -name '.build' -o -name 'DerivedData' -o -name '.DS_Store' \) -prune -o -print \
    | LC_ALL=C sort \
    | sed 's|^\./||' \
    | while IFS= read -r path; do
        depth=$(printf '%s' "$path" | awk -F'/' '{print NF-1}')
        name=$(basename "$path")
        [ -d "$path" ] && name="${name}/"
        printf '%*s%s\n' "$((depth * 2))" '' "$name"
      done
)"

cat > "$OUT" <<EOF
# Project Structure

*Auto-generated by \`Tooling/print_structure.sh\` — regenerated each phase. Do not edit by hand.*

_Last generated: ${NOW}_

\`\`\`
BangForBuck/
${BODY}
\`\`\`
EOF

echo "wrote $OUT"
